trigger:
    branches:
       include:
         - main
pool:
   vmImage: 'ubuntu-latest'
steps:

    - task: JavaToolInstaller@0
      displayName: java installer
      inputs:
        versionSpec: '8'
        jdkArchitectureOption: 'x64'
        cleanDestinationDirectory: false
    
    - task: Maven@3
      displayName: 'Maven build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
    
    
  #  - task: PublishBuildArtifacts@1
  #    inputs:
  #      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #      ArtifactName: 'drop'
  #      publishLocation: 'Container'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'vprofile'
        publishLocation: 'pipeline'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'https://github.com/anilkumarpuli/VProfile/blob/master/Dockerfile'
        Contents: 'Dockerfile'
        TargetFolder: '.'
  
   