trigger:
    branches:
       include:
         - main

pool:
   vmImage: 'ubuntu-latest'


steps:
   - task: Maven@3
     displayName: 'Maven build'
     inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        options: '-DskipTests=true'
        publishJUnitResults: false
   - task: PublishBuildArtifacts@1
     inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'drop'
       publishLocation: 'Container'
   - task: CopyFiles@2
     inputs:
       SourceFolder: 'https://github.com/anilkumarpuli/VProfile/blob/master/Dockerfile'
       Contents: 'Dockerfile'
       TargetFolder: '.'
   - task: Docker@2
     displayName: 'Build Docker image'
     inputs:
      command: build
      dockerfile: '.'
      imageName: 'mydockerfile:$(Build.BUILD_NUMBER)'
      includeLatestTag: true 
   
   